version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: online_cinema
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db/online_cinema
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
